---
- name: Verifying if ipa client is installed
  stat:
    path: /etc/ipa/default.conf
  register: stat_result

- name: Adding new hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost {{ ansible_hostname }} {{ ansible_hostname }}.domain.com.br"
  when: stat_result.stat.exists == False

- name: Changing server ansible_hostname
  hostname:
    name: "{{ ansible_hostname }}.domain.com.br"
  when: stat_result.stat.exists == False

- name: FreeIPA and SSSD-Tools installation
  package:
    name: "{{ item }}"
    state: present
  when: stat_result.stat.exists == False
  loop:
    - freeipa-client
    - sssd-tools

- name: FreeIPA and SSSD-Tools installation
  shell: ipa-client-install -U --server=ipa.domain.com.b --domain=domain.com.b --realm=DOMAIN.COM.BR --mkhomedir -psvc_join -weMae5aiv --force-join --enable-dns-updates
  when: stat_result.stat.exists == False
